---
title: "R空间分析"
author:
  - 吴温泉
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---
# Spatial Data
```{r}
# https://bookdown.org/xiangyun/masr/chap-spatial-analysis.html
library(sp)
library(RColorBrewer)
library(raster)
library(lattice)
library(latticeExtra)
library(terra)
library(sf)

```

# intro of sf package
```{r}
# https://zhuanlan.zhihu.com/p/29743287
library("sf")
nc <- st_read(system.file("shape/nc.shp", package="sf"))
class(nc)
attr(nc, 'sf_column')
methods(class = 'sf')

nc.no_sf <- as.data.frame(nc)     
class(nc.no_sf)

# operation
x <- st_point(c(1,2));x;class(x);str(x);plot(x)

p <- rbind(c(3.2,4), c(3,4.6), c(3.8,4.4), c(3.5,3.8), c(3.4,3.6), c(3.9,4.5))
mp<-st_multipoint(p);mp;class(mp);str(mp);plot(mp)

s1 <- rbind(c(0,3),c(0,4),c(1,5),c(2,5))
ls <- st_linestring(s1);ls;class(ls);str(ls);plot(ls)

s2 <- rbind(c(0.2,3), c(0.2,4), c(1,4.8), c(2,4.8))
s3 <- rbind(c(0,4.4), c(0.6,5))
mls <- st_multilinestring(list(s1,s2,s3));mls;class(mls);str(mls);plot(mls)

p1 <- rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0))
p2 <- rbind(c(1,1), c(1,2), c(2,2), c(1,1))
pol <-st_polygon(list(p1,p2));pol;class(pol);str(pol);plot(pol)

p1 <- rbind(c(0,0), c(1,0), c(3,2), c(2,4), c(1,4), c(0,0))
p2 <- rbind(c(1,1), c(1,2), c(2,2), c(1,1))
pol <-st_polygon(list(p1,p2))
p3 <- rbind(c(3,0), c(4,0), c(4,1), c(3,1), c(3,0))
p4 <- rbind(c(3.3,0.3), c(3.8,0.3), c(3.8,0.8), c(3.3,0.8), c(3.3,0.3))[5:1,]
p5 <- rbind(c(3,3), c(4,2), c(4,3), c(3,3))
mpol <- st_multipolygon(list(list(p1,p2), list(p3,p4), list(p5)));mpol;class(mpol);str(mpol);plot(mpol)

gc <- st_geometrycollection(list(mp, mpol, ls))
gc;class(gc);str(gc);plot(gc)

# coding type
x <-  st_linestring(matrix(10:1,5))
st_as_text(x)
st_as_binary(x)

# Coodinate reference transformations
st_crs(nc)<-"+proj=longlat +datum=NAD27 +no_defs +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat"
#读入数据没有任何crs属性时，需要直接设置crs属性，可以赋给一个projstring字符串，也可以设置WSG84空间投影代码。
nc.web_mercator <- st_transform(nc, 3857) 

# sf to sp / sp to sf
nc.sp <-  as(nc, "Spatial")
nc2 <-  st_as_sf(nc.sp)

```

# Spatial Dependence
```{r Spatial Dependence}
# https://zhuanlan.zhihu.com/p/368904812
# 一阶邻接矩阵
library(pacman)
p_load(
  sf,
  sp,
  spdep
)
nc <- st_read(system.file('shape/nc.shp', package = 'sf'))
nc.sp <- as(nc, 'Spatial')

nb <- poly2nb(nc)
nb2 <- poly2nb(nc, queen = F)

## 绘制邻接关系图
plot(st_geometry(nc), main ='QUEEN')
plot(nb, st_geometry(nc), add = T, col = 'red')

plot(st_geometry(nc), main ='ROOK')
plot(nb, st_geometry(nc),arrows = T, add = T, col = 'blue')

## sp object
nb.sp <- poly2nb(nc.sp)
plot(nc.sp, main = 'sp')
plot(nb.sp, nc.sp, add = T, col = 'red')

# 高阶邻接矩阵
nb.lag <- nblag(nb, maxlag = 3)
nb.lag2 <- nblag_cumul(nb.lag)

# 点要素空间邻接矩阵
ncpoint <- st_centroid(st_geometry(nc))

## st obj
nc.coord <- coordinates(nc.sp)

## k邻接
nb.k <- knearneigh(ncpoint) %>% knn2nb()
nb.k2 <- knearneigh(ncpoint, k=2) %>% knn2nb()
nb.k4 <- knearneigh(ncpoint, k=4) %>% knn2nb()

plot(st_geometry(nc), main = 'k=1')
plot(nb.k,ncpoint,arrows = T, add =T, col = 'red')

plot(st_geometry(nc), main = 'k=2')
plot(nb.k2,ncpoint,add =T, col = 'red')

plot(st_geometry(nc), main = 'k=4')
plot(nb.k4,ncpoint,add =T, col = 'red')

nbdists(nb.k,ncpoint)
nbdists(nb.k2,ncpoint)
nbdists(nb.k4,ncpoint)

# 基于距离范围
max = nbdists(nb.k,ncpoint) %>% unlist() %>% max()
nb.dist <- dnearneigh(ncpoint, 0 , 0.5*max)
nb.dist2 <- dnearneigh(ncpoint, 0 , max)
nb.dist3 <- dnearneigh(ncpoint, 0 , 1.5*max)

plot(st_geometry(nc), main ='small')
plot(nb.dist, ncpoint, add = T, col = 'red')
plot(st_geometry(nc), main ='middle')
plot(nb.dist2, ncpoint, add = T, col = 'red')
plot(st_geometry(nc), main ='big')
plot(nb.dist3, ncpoint, add = T, col = 'red')

# 基于图形关系
tri2nb(coords, row.names = NULL)
nb.tri <- tri2nb(ncpoint)
plot(st_geometry(nc),main = 'tri')
plot(nb.tri,ncpoint,add = T, col= 'red')

graph <-  gabrielneigh(ncpoint)
nb.graph <- graph2nb(graph)
plot(st_geometry(nc), main = "Gabriel neighbor graph")
plot(nb.graph, ncpoint, add = T, col = "red")

graph2 <- relativeneigh(ncpoint)
nb.graph2 <- graph2nb(graph2)
plot(st_geometry(nc), main = "Relative neighbor graph")
plot(nb.graph2, ncpoint, add = T, col = "red")

library(dbscan)
graph3 <- soi.graph(nb.tri, ncpoint)
nb.graph3 <- graph2nb(graph3)
plot(st_geometry(nc), main = "SOI neighbor graph")
plot(nb.graph3, ncpoint, add = T, col = "red")

# 空间权重
w1 <- nb2listw(nb)
w2 <- nb2mat(nb,style = 'B')
w3 <- listw2mat(w1)

nb2listwdist(nb,nc)
nb2listwdist(nb.k2,nc)

# 空间自相关指数
weighted.nc <- nb2listw(nb)
moran.plot(nc$PERIMETER,weighted.nc)
a <- moran.plot(nc$PERIMETER, weighted.nc)
head(a)
moran(nc$PERIMETER, weighted.nc, n = nrow(nc), S0 = Szero(weighted.nc))
# I is moran index

moran.test(nc$PERIMETER,weighted.nc)

moran.mc(nc$PERIMETER,weighted.nc, nsim = 1000)

# 局部莫兰指数, aka LISA
localI <- localmoran(nc$PERIMETER, weighted.nc)
head(localI)

# manual calculate weight matrix
w0 <-  nb2mat(nb, style = 'B')

ww2 <-  w0/rowSums(w0)

wu2 <- w0/sum(w0)

wc2 <- ncol(w0)*w0/sum(w0)

wmin2 <-  w0/min(max(colSums(w0)), max(rowSums(w0)))

Q <- w0/sqrt(rowSums(w0))
ws2 <- ncol(w0)*Q/sum(Q)

# manual calculate moran

X <-  nc$PERIMETER
n <- length(X)

w0 <-  nb2mat(nb, style = 'B')
w2 <- w0/sum(w0)

Z <- scale(X, scale = F)

ncol(w2)*cov(Z, w2%*%Z)/(var(Z)*sum(w2))
```

# Spatial Regression
```{r}
# https://zhuanlan.zhihu.com/p/432716121
# formulas missed in the url
library(spatialreg)
library(albersusa)
library(sf)
library(tidyverse)
library(socviz)
usa <- albersusa::counties_sf(proj = "laea") %>%
  mutate(fips = as.character(fips)) %>%
  left_join(socviz::county_data, by = c("fips" = "id"))

data <- st_drop_geometry(usa)
model <- lm(hh_income ~ black , data = data)
summary(model)

## moran
nb <- poly2nb(usa)
listW <- nb2listw(nb, zero.policy = T)

moran.plot(usa$hh_income, listW,
           zero.policy = T,
           labels = F,
           pch = 20 ,
           cex = 0.1)

## Spatial lag Model
sl_model <- lagsarlm(hh_income ~ black, data = data,
                     listw = listW, zero.policy = T)

summary(sl_model)
## Spatial Err model
se_model <- errorsarlm(hh_income ~ black, data = data,
                       listw = listW, zero.policy = T)
summary(se_model)
## Spatial lag err model
sd_model <- errorsarlm(hh_income ~ black, data = data,
                       listw = listW, zero.policy = T,
                       Durbin = T)
summary(sd_model)
```


# Boston house prise
```{r}
# https://mp.weixin.qq.com/s?src=11&timestamp=1647071496&ver=3671&signature=YhCKvOo-**YRDz7u7e--ixeimkQxY7XVMkyqhZV47-NEuhe8kd6QDySAbloX*y3SD8QqfJLI3ENLeOxBEi*tSuRlrk1Q4rCmOiHZRjTEfWk7ef2-TFu4Sxtz8QrIRvYf&new=1
data(boston)

str(boston.c)

hr0 <- lm(log(MEDV) ~ CRIM + ZN + INDUS + CHAS + I(NOX^2) +I(RM^2) +
            AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B +
            log(LSTAT), data = boston.c)
summary(hr0)
logLik(hr0)

gp0 <- lm(log(CMEDV) ~ CRIM + ZN + INDUS + CHAS + I(NOX^2) + I(RM^2) +
                    AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B + log(LSTAT), data = boston.c)
summary(gp0)
logLik(gp0)

lm.morantest(hr0,nb2listw(boston.soi))

# spatial err model 
gp1 <-  errorsarlm(log(CMEDV) ~  CRIM + ZN + INDUS + CHAS + I(NOX^2) + I(RM^2) +
                    AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B + log(LSTAT), data = boston.c,listw = nb2listw(boston.soi),
                   method = 'Matrix', control = list(tol.opt = .Machine$double.eps^(1/4)))

summary(gp1)

# spatial lag moedl
gp1 <-  lagsarlm(log(CMEDV) ~  CRIM + ZN + INDUS + CHAS + I(NOX^2) + I(RM^2) +
                    AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B + log(LSTAT), data = boston.c,listw = nb2listw(boston.soi),
                   method = 'Matrix', control = list(tol.opt = .Machine$double.eps^(1/4)))
summary(gp1)


# panal spatial 
data(produc)
```


# uk_london_boroughs

```{R}

# https://zhuanlan.zhihu.com/p/283103988
# https://zhuanlan.zhihu.com/p/285555989
library(pacman)
p_load(spatstat, sp, rgeos, maptools, GISTools, tmap,
       sf, geojson, geojsonio, tmaptools, tidyverse, raster, fpc, dbscan,geomultistar)

LondonBoroughs <- st_read('./spatial_analysis/data/London_Borough_Excluding_MHW.shp')

```

# xiangyun
```{r}
# https://bookdown.org/xiangyun/masr/chap-spatial-analysis.html

library(sp)
data(meuse)
coordinates(meuse) <- ~x+y

proj4string(meuse) <- CRS("+init=epsg:28992")
plot(meuse)


meuse = st_as_sf(meuse)
meuse.longlat =st_transform(meuse,crs = "EPSG:4326")
plot(meuse.longlat['zinc'],axes = TRUE)

library(sf)
nc <- st_read(system.file('shape/nc.shp', package = 'sf'))
library(mapview)
mapview(nc, zcol = c("SID74", "SID79"), alpha.regions = 1.0 , legend = TRUE)

# redal package
# https://github.com/geodacenter/rgeoda/
library(rgeoda)
library(sf)

guerry <- st_read(system.file('extdata','guerry.shp', package = 'rgeoda'))

queen.w <- queen_weights(guerry)

lisa <- local_moran(queen.w,crm_prp)
lisa_colors <- lisa_colors(lisa)
lisa_labels <- lisa_labels(lisa)
lisa_clusters <- lisa_clusters(lisa)

plot(st_geometry(guerry),
     col = sapply(lisa_clusters, function(x){
       lisa_colors[[x + 1 ]]
     }),
     border = "#333333", lwd = 0.2)

title(main = "Local Moran Map of Crm_prs")
legend("bottomleft",
  legend = lisa_labels,
  fill = lisa_colors,
  border = "#eeeeee"
)

# vis

plot(meuse, axes = TRUE)
crs.longlat <-  CRS("+init=epsg:4326")
meuse.longlat <- spTransform(meuse, crs.longlat)
plot(meuse.longlat, axes = TRUE)

# raster FIJI
install.packages('echarts4r')
library(echarts4r)
quakes %>% 
  e_charts(x = long) %>% 
  e_geo(
    roam = TRUE,
    boundingCoords = list(
      c(185, -10),
      c(165, -40)
    )
  ) %>% 
  e_scatter(
    serie = lat,
    size = mag,
    name = 'Fiji earthquakes',
    coord_system = 'geo',
  ) %>% 
  e_visual_map(
    serie = mag,
    scale = e_scale,
    inRange = list(color = terrain.colors(10))
  ) %>% 
  e_tooltip()
```

# user2020
```{r}
# https://edzer.github.io/UseR2020/
if (!require(remotes))
  install.packages("remotes")
remotes::install_github("r-spatial/stars")

install.packages("starsdata", repos = "http://pebesma.staff.ifgi.de", type = "source")

library(stars)

library(ggplot2)
data("Produc", package ='plm')
ggplot(Produc) + geom_raster(aes(y = state, x = year, fill = pcap))

s = st_as_stars(Produc, y_decreasing = FALSE)
s = st_apply(s, 1, function(x) x/mean(x)) %>% 
  st_set_dimensions(names = c('year','state'))
s

pr = as.data.frame(s)
head(pr)
ggplot(pr) + geom_raster(aes(y = state, x = year, fill = pcap))

library(maps)
states.m = map('state',plot = FALSE, fill = TRUE)
st = st_as_sf(states.m)[-8,]
match(tolower(st_get_dimension_values(s, 'state')), sub(' ', '_',st$ID))

(s_sf = st_set_dimensions(s, 'state', values = st_geometry(st)))

s_sf_y1 = s_sf[,1]
(s_sf_y1 = adrop(s_sf_y1))

sf = st_as_sf(s_sf_y1)
plot(sf)

# 北卡罗来纳州 SIDS
nc <-  read_sf(system.file('gpkg/nc.gpkg', package = 'sf'))
nc.df <- st_set_geometry(nc, NULL)
head(nc.df)

mat <- as.matrix(nc.df[c("BIR74", "SID74", "NWBIR74", "BIR79", "SID79", "NWBIR79")])
dim(mat) = c(county = 100, var =3 , year = 2)
dimnames(mat) = list(county = nc$NAME, var = c("BIR", "SID", "NWBIR"), year = c(1974, 1979))
nc.st <- st_as_stars(pop = mat)
nc.geom <- st_set_dimensions(nc.st, 1, st_geometry(nc))

plot(st_apply(nc.geom, c(1,2), sum), key.pos = 4)


nc.sum <- sapply(split(nc.geom,2), sum)
nc.su
IR <- nc.sum[2]/nc.sum[1]
nc.SIR <- st_apply(nc.geom, c(1,3), function(x) (x[2]/x[1]/IR))
plot(nc.SIR, breaks = c(0,.25,.5,.75,.9,1.1,1.5,2.5,3.5,5),
     pal = rev(RColorBrewer::brewer.pal(9, "RdBu")))


g <- read_stars(system.file('external/test.grd', package = 'raster'))
plot(g, col = viridis::viridis(11), breaks = "equal")

(g.sf = st_as_sf(g, na.rm = FALSE))
plot(g.sf, border = 'grey',  pal = viridis::viridis(9), nbreaks = 10)

r <- read_stars(system.file('pictures/Rlogo.jpg', package = 'rgdal'))

plot(r, breaks  ='equal')


(r.rgb = st_rgb(r))


r.rgb[[1]][1:3,1]

plot(r.rgb)

L7file <- system.file('tif/L7_ETMs.tif', package = 'stars')
(L7 <- read_stars(L7file))

plot(L7)

plot(L7, join_zlim = FALSE)

par(mfrow = c(1,2))
plot(L7, rgb = c(3,2,1), reset = FALSE, main = 'RGB')
plot(L7, rgb = c(4,3,2), main = "False color (NIR-R-G)")

bb <- st_bbox(c(xmin = -10 , xmax = 20 ,ymin = 40, ymax = 60), crs = 4326)
(x = st_as_stars(bb, dx = 1, dy = 1))

library(rnaturalearth)
ne <- ne_countries(returnclass =  'sf', continent = 'europe') %>% 
  st_set_precision(1e8)

ne$pop_dens <- units::set_units(ne$pop_est  / st_area(ne), 1/(km^2))
plot(ne['pop_dens'], reset = FALSE, extent = bb)

pop <- st_rasterize(ne['pop_dens'],x)
plot(st_as_sf(pop, na.rm = FALSE), add = TRUE, border = 'grey')
```


# ref
```{r, echo=FALSE}
# https://oscarperpinan.github.io/rastervis/
# https://xiangyun.rbind.io/2022/02/draw-china-maps/
  
```