---
title: "R空间分析"
author:
  - 吴温泉
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---
# Spatial Dependence
```{r Spatial Dependence}
# https://zhuanlan.zhihu.com/p/368904812
# 一阶邻接矩阵
library(pacman)
p_load(
  sf,
  sp,
  spdep
)
nc <- st_read(system.file('shape/nc.shp', package = 'sf'))
nc.sp <- as(nc, 'Spatial')

nb <- poly2nb(nc)
nb2 <- poly2nb(nc, queen = F)

## 绘制邻接关系图
plot(st_geometry(nc), main ='QUEEN')
plot(nb, st_geometry(nc), add = T, col = 'red')

plot(st_geometry(nc), main ='ROOK')
plot(nb, st_geometry(nc),arrows = T, add = T, col = 'blue')

## sp object
nb.sp <- poly2nb(nc.sp)
plot(nc.sp, main = 'sp')
plot(nb.sp, nc.sp, add = T, col = 'red')

# 高阶邻接矩阵
nb.lag <- nblag(nb, maxlag = 3)
nb.lag2 <- nblag_cumul(nb.lag)

# 点要素空间邻接矩阵
ncpoint <- st_centroid(st_geometry(nc))

## st obj
nc.coord <- coordinates(nc.sp)

## k邻接
nb.k <- knearneigh(ncpoint) %>% knn2nb()
nb.k2 <- knearneigh(ncpoint, k=2) %>% knn2nb()
nb.k4 <- knearneigh(ncpoint, k=4) %>% knn2nb()

plot(st_geometry(nc), main = 'k=1')
plot(nb.k,ncpoint,arrows = T, add =T, col = 'red')

plot(st_geometry(nc), main = 'k=2')
plot(nb.k2,ncpoint,add =T, col = 'red')

plot(st_geometry(nc), main = 'k=4')
plot(nb.k4,ncpoint,add =T, col = 'red')

nbdists(nb.k,ncpoint)
nbdists(nb.k2,ncpoint)
nbdists(nb.k4,ncpoint)

# 基于距离范围
max = nbdists(nb.k,ncpoint) %>% unlist() %>% max()
nb.dist <- dnearneigh(ncpoint, 0 , 0.5*max)
nb.dist2 <- dnearneigh(ncpoint, 0 , max)
nb.dist3 <- dnearneigh(ncpoint, 0 , 1.5*max)

plot(st_geometry(nc), main ='small')
plot(nb.dist, ncpoint, add = T, col = 'red')
plot(st_geometry(nc), main ='middle')
plot(nb.dist2, ncpoint, add = T, col = 'red')
plot(st_geometry(nc), main ='big')
plot(nb.dist3, ncpoint, add = T, col = 'red')

# 基于图形关系
tri2nb(coords, row.names = NULL)
nb.tri <- tri2nb(ncpoint)
plot(st_geometry(nc),main = 'tri')
plot(nb.tri,ncpoint,add = T, col= 'red')

graph <-  gabrielneigh(ncpoint)
nb.graph <- graph2nb(graph)
plot(st_geometry(nc), main = "Gabriel neighbor graph")
plot(nb.graph, ncpoint, add = T, col = "red")

graph2 <- relativeneigh(ncpoint)
nb.graph2 <- graph2nb(graph2)
plot(st_geometry(nc), main = "Relative neighbor graph")
plot(nb.graph2, ncpoint, add = T, col = "red")

library(dbscan)
graph3 <- soi.graph(nb.tri, ncpoint)
nb.graph3 <- graph2nb(graph3)
plot(st_geometry(nc), main = "SOI neighbor graph")
plot(nb.graph3, ncpoint, add = T, col = "red")

# 空间权重
w1 <- nb2listw(nb)
w2 <- nb2mat(nb,style = 'B')
w3 <- listw2mat(w1)

nb2listwdist(nb,nc)
nb2listwdist(nb.k2,nc)

# 空间自相关指数
weighted.nc <- nb2listw(nb)
moran.plot(nc$PERIMETER,weighted.nc)
a <- moran.plot(nc$PERIMETER, weighted.nc)
head(a)
moran(nc$PERIMETER, weighted.nc, n = nrow(nc), S0 = Szero(weighted.nc))
# I is moran index

moran.test(nc$PERIMETER,weighted.nc)

moran.mc(nc$PERIMETER,weighted.nc, nsim = 1000)

# 局部莫兰指数, aka LISA
localI <- localmoran(nc$PERIMETER, weighted.nc)
head(localI)

# manual calculate weight matrix
w0 <-  nb2mat(nb, style = 'B')

ww2 <-  w0/rowSums(w0)

wu2 <- w0/sum(w0)

wc2 <- ncol(w0)*w0/sum(w0)

wmin2 <-  w0/min(max(colSums(w0)), max(rowSums(w0)))

Q <- w0/sqrt(rowSums(w0))
ws2 <- ncol(w0)*Q/sum(Q)

# manual calculate moran

X <-  nc$PERIMETER
n <- length(X)

w0 <-  nb2mat(nb, style = 'B')
w2 <- w0/sum(w0)

Z <- scale(X, scale = F)

ncol(w2)*cov(Z, w2%*%Z)/(var(Z)*sum(w2))
```

# Spatial Regression
```{r}
# https://zhuanlan.zhihu.com/p/432716121
# formulas missed in the url
library(spatialreg)
library(albersusa)
library(sf)
library(tidyverse)
library(socviz)
usa <- albersusa::counties_sf(proj = "laea") %>%
  mutate(fips = as.character(fips)) %>%
  left_join(socviz::county_data, by = c("fips" = "id"))

data <- st_drop_geometry(usa)
model <- lm(hh_income ~ black , data = data)
summary(model)

## moran
nb <- poly2nb(usa)
listW <- nb2listw(nb, zero.policy = T)

moran.plot(usa$hh_income, listW,
           zero.policy = T,
           labels = F,
           pch = 20 ,
           cex = 0.1)

## Spatial lag Model
sl_model <- lagsarlm(hh_income ~ black, data = data,
                     listw = listW, zero.policy = T)

summary(sl_model)
## Spatial Err model
se_model <- errorsarlm(hh_income ~ black, data = data,
                       listw = listW, zero.policy = T)
summary(se_model)
## Spatial lag err model
sd_model <- errorsarlm(hh_income ~ black, data = data,
                       listw = listW, zero.policy = T,
                       Durbin = T)
summary(sd_model)
```


# Boston house prise
```{r}
# https://mp.weixin.qq.com/s?src=11&timestamp=1647071496&ver=3671&signature=YhCKvOo-**YRDz7u7e--ixeimkQxY7XVMkyqhZV47-NEuhe8kd6QDySAbloX*y3SD8QqfJLI3ENLeOxBEi*tSuRlrk1Q4rCmOiHZRjTEfWk7ef2-TFu4Sxtz8QrIRvYf&new=1
data(boston)

str(boston.c)

hr0 <- lm(log(MEDV) ~ CRIM + ZN + INDUS + CHAS + I(NOX^2) +I(RM^2) +
            AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B +
            log(LSTAT), data = boston.c)
summary(hr0)
logLik(hr0)

gp0 <- lm(log(CMEDV) ~ CRIM + ZN + INDUS + CHAS + I(NOX^2) + I(RM^2) +
                    AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B + log(LSTAT), data = boston.c)
summary(gp0)
logLik(gp0)

lm.morantest(hr0,nb2listw(boston.soi))

# spatial err model 
gp1 <-  errorsarlm(log(CMEDV) ~  CRIM + ZN + INDUS + CHAS + I(NOX^2) + I(RM^2) +
                    AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B + log(LSTAT), data = boston.c,listw = nb2listw(boston.soi),
                   method = 'Matrix', control = list(tol.opt = .Machine$double.eps^(1/4)))

summary(gp1)

# spatial lag moedl
gp1 <-  lagsarlm(log(CMEDV) ~  CRIM + ZN + INDUS + CHAS + I(NOX^2) + I(RM^2) +
                    AGE + log(DIS) + log(RAD) + TAX + PTRATIO + B + log(LSTAT), data = boston.c,listw = nb2listw(boston.soi),
                   method = 'Matrix', control = list(tol.opt = .Machine$double.eps^(1/4)))
summary(gp1)


# panal spatial 
data(produc)
```